In [18]:
import numpy as np

matrix = np.array([[1, 1, 1],[1, 1, 1],[1, 1,1]])
a= matrix @ matrix
print(a)
# task1

first_matrix = np.arange(3, 12)

first_matrix=first_matrix.reshape(3,3)
first_matrix

[[3 3 3]
 [3 3 3]
 [3 3 3]]


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
# task 2

np.max(first_matrix)
np.min(first_matrix)
np.mean(first_matrix)

np.float64(7.0)

In [13]:
second_matrix=first_matrix**2
second_matrix.reshape(3, 3)
second_matrix=second_matrix.reshape(3, 3)
second_matrix

array([[  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
third_matrix=np.vstack( [first_matrix, second_matrix])



array([[  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [20]:
third_matrix@first_matrix

array([[ 348,  398,  448],
       [ 978, 1127, 1276],
       [1932, 2234, 2536]])

In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])
arr

Last element from 2nd dim:  10


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])